---
- name: Ensure apt cache is updated
  apt:
    update_cache: yes

- name: Install Nginx Web Server
  apt:
    name: nginx
    state: present

- name: Ensure Nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy custom index.html webpage
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
